export { PedagogicalEngine, pedagogicalEngine } from "./PedagogicalEngine";
export { pedagogicalEventBus } from "./events";
export * from "./types";
export { detectPedagogicalConflicts } from "./conflict-detector";
export { recalculateHourVolumes, recalculatePedagogicalStats } from "./hours-calculator";
export { logPedagogicalChange, listPedagogicalChanges, revertPedagogicalChange, listEntityPedagogicalHistory, comparePedagogicalVersions, findPedagogicalSnapshot } from "./change-history";
export { loadPilotagePayload } from "./intelligence/pilotage-service";
export { analyzePedagogicalCoherence } from "./intelligence/coherence-analyzer";
export { computeBoCoverageReport } from "./intelligence/bo-coverage";
export { searchPedagogicalDocuments } from "./intelligence/search";
export { buildDocumentChain, buildDocumentChainByCompetence } from "./intelligence/document-chain";
export { buildPedagogicalSuggestions } from "./intelligence/pedagogical-suggestions";
export { triggerPedagogicalAnalysis } from "./intelligence/coherence-trigger";
